server:
  port : 8086
  servlet:
     context-path: /api/${parcom.api.version}
redis:
  host: "pc-user-cache-redis"
  port: 6379
  ttl: 300
parcom:
  security:
    permitted:
      -
        /users/reset/**
  kafka:
    bootstrap-address: pc-kafka:9092
    topic:
      user: user
    group:
      user-cache: user-cache
  api:
    version: v1
  services:
    -
      name: classroom
      host: pc-classroom
      port: 8080
      version: v1
spring:
  application.name: pc-user-cache
  hateoas:
    use-hal-as-default-json-media-type: false

management:
  endpoints:
    metrics:
      enabled: true
    web:
      exposure:
        include: "health,prometheus"
  metrics:
    tags:
      application: ${spring:application:name}
